package constant;

public enum GameClass {
	VOID, PALADIN, BERSERKER, ASSASSIN, CROSSBOWER, HEALER, ENGINEER, DAMAGE_FIRE, CONTROL_ICE, HUNTER, MELE, RANK, FIGHTER, ARCHER, SUPPORT, WIZARD, HIGH, MIDDLE
}
